MTI\UserBackOfficeBundle\Entity\Call:
    type: entity
    table: call
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        userid:
            type: integer
            length: 11
        type:
            type: integer
            length: 11
        created:
            type: datetime

    lifecycleCallbacks:
        prePersist: [setCreatedValue]