mti_hello_world:
    resource: "@MTIHelloWorldBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    pattern:   /
    defaults:  { _controller: MTIApiProjectHomeBundle:Home:index }